cmd_drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o := arm-linux-gnueabi-gcc -Wp,-MD,drivers/net/wireless/atmel/at_pwr_dev/.atwilc_debugfs.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabi/4.7/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -DBT_FIRMWARE=\"bt_firmware.bin\" -I drivers/net/wireless/atmel/at_pwr_dev// -I drivers/net/wireless/atmel/at_pwr_dev//../wilc3000/ -DPLAT_SAMA5D4 -DATWILC_SDIO -DATWILC_ASIC_A0 -DATL_PLATFORM=ATL_LINUXKERNEL -Wno-unused-function -DUSE_WIRELESS  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(atwilc_debugfs)"  -D"KBUILD_MODNAME=KBUILD_STR(at_pwr_dev)" -c -o drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.c

source_drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o := drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.c

deps_drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o := \
    $(wildcard include/config/dbg.h) \

drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o: $(deps_drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o)

$(deps_drivers/net/wireless/atmel/at_pwr_dev/atwilc_debugfs.o):
