cmd_drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o := arm-linux-gnueabi-gcc -Wp,-MD,drivers/net/wireless/atmel/wilc3000/.atwilc_wfi_netdevice.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabi/4.7/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -I drivers/net/wireless/atmel/wilc3000// -I drivers/net/wireless/atmel/wilc3000//../at_pwr_dev/ -DSTA_FIRMWARE=\"wifi_firmware.bin\" -DAP_FIRMWARE=\"wifi_firmware_ap.bin\" -DP2P_CONCURRENCY_FIRMWARE=\"wifi_firmware_p2p_concurrency.bin\" -DBT_FIRMWARE=\"bt_firmware.bin\" -DPLAT_SAMA5D4 -D__DRIVER_VERSION__=\"5.0.1\" -D__FW_VERSION__=\"5.0.0\" -DATWILC_SDIO -DATWILC_ASIC_A0 -DCONNECT_DIRECT -DATWILC_PARSE_SCAN_IN_HOST -DAGING_ALG -DDISABLE_PWRSAVE_AND_SCAN_DURING_IP -DATL_PLATFORM=ATL_LINUXKERNEL -Wno-unused-function -DUSE_WIRELESS -DATWILC_BT_COEXISTENCE -DDOWNLOAD_BT_FW\  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(atwilc_wfi_netdevice)"  -D"KBUILD_MODNAME=KBUILD_STR(wilc3000)" -c -o drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.c

source_drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o := drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.c

deps_drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o := \

drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o: $(deps_drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o)

$(deps_drivers/net/wireless/atmel/wilc3000/atwilc_wfi_netdevice.o):
